export const DELETE_POINT = 'DELETE_POINT'

export const INCREMENT = 'INCREMENT'

export const SET_SELECT_POINTS = 'SET_SELECT_POINTS'

export const SET_DATE = 'SET_DATE'

export const FILTER_BY_DATE = 'FILTER_BY_DATE'

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST'

export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'
